version: '3.7'

services: 
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment: 
      - ENVIRONMENT=production
      - SECRET_KEY=nq#osk$$vggb3z756w%h8%s*as%=5pduig9h0bo7eb6yub+3=)x
      - DEBUG=0
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_tUaWXtnixlSAbpYm0JObaU0M00DeT1dMSi
      - STRIPE_TEST_SECRET_KEY=sk_test_vcP1kclmdcfRhQ0Ww5BpOmTR00TvCbmOcj
    ports:
      - 8000:8000
    depends_on: 
      - db
  
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres