# Generated by Django 4.2 on 2023-04-14 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_created_on_book_description_book_link_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ("-created_on",),
                "permissions": [("special_status", "Can read all books")],
            },
        ),
    ]
